<?php

namespace Database\Seeders;

use App\Models\HsCode;
use Illuminate\Database\Seeder;

class HsCodeSeeder extends Seeder
{
    public function run(): void
    {
        $commodities = [
            // ============================================================
            // 1. TEXTILES, PASHMINA & APPAREL
            // ============================================================
            [
                'code' => '6214.20.00',
                'wco_code' => '6214.20',
                'nepal_tariff_code' => '6214.20.00',
                'commodity_name' => 'Pashmina & Cashmere Shawls, Scarves & Stoles',
                'description' => 'Fine Chyangra goat cashmere and pashmina woven shawls, stoles, mufflers, and scarves.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Nepal Pashmina Hallmark / Certificate of Origin recommended for preferential duty.',
                'is_popular' => true,
                'search_keywords' => 'pashmina, cashmere, shawl, stoles, scarf, scarves, muffler, chyangra, woven wool',
            ],
            [
                'code' => '6214.10.00',
                'wco_code' => '6214.10',
                'nepal_tariff_code' => '6214.10.00',
                'commodity_name' => 'Silk & Silk-Blend Shawls, Scarves & Wraps',
                'description' => 'Shawls, scarves, mufflers, mantillas and veils of pure silk or silk waste blends.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Declare silk percentage on invoice.',
                'is_popular' => true,
                'search_keywords' => 'silk, silk scarf, silk shawl, wraps, dupion silk, mulberry silk',
            ],
            [
                'code' => '6110.12.00',
                'wco_code' => '6110.12',
                'nepal_tariff_code' => '6110.12.00',
                'commodity_name' => 'Knitted Cashmere Sweaters, Pullovers & Cardigans',
                'description' => 'Jerseys, pullovers, cardigans, waistcoats and similar articles, knitted or crocheted of Kashmir (cashmere) goats.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => '100% Cashmere or blend must be declared.',
                'is_popular' => true,
                'search_keywords' => 'cashmere sweater, knitted cardigan, pullover, jumper, knitwear, cashmere',
            ],
            [
                'code' => '6110.11.00',
                'wco_code' => '6110.11',
                'nepal_tariff_code' => '6110.11.00',
                'commodity_name' => 'Hand-Knitted Woolen Sweaters, Jumpers & Cardigans',
                'description' => 'Jerseys, pullovers, cardigans, waistcoats, knitted of pure sheep or lamb wool.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Hand-knitted Nepal craft product.',
                'is_popular' => true,
                'search_keywords' => 'wool sweater, woolen jumper, handmade knitwear, warm jacket, fleece lined wool',
            ],
            [
                'code' => '6204.62.00',
                'wco_code' => '6204.62',
                'nepal_tariff_code' => '6204.62.00',
                'commodity_name' => 'Cotton Trousers, Kurthas & Casual Apparel',
                'description' => 'Women or girls cotton trousers, bib and brace overalls, breeches and shorts.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Commercial textile export.',
                'is_popular' => true,
                'search_keywords' => 'cotton pants, kurtha, trousers, cotton garments, apparel, clothing',
            ],
            [
                'code' => '6109.10.00',
                'wco_code' => '6109.10',
                'nepal_tariff_code' => '6109.10.00',
                'commodity_name' => 'Cotton T-Shirts, Singlets & Printed Tops',
                'description' => 'T-shirts, singlets and other vests, knitted or crocheted, of cotton.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Standard commercial apparel.',
                'is_popular' => true,
                'search_keywords' => 't-shirt, cotton tshirt, graphic tee, singlet, polo shirt',
            ],
            [
                'code' => '6217.10.00',
                'wco_code' => '6217.10',
                'nepal_tariff_code' => '6217.10.00',
                'commodity_name' => 'Himalayan Nettle (Allo) & Natural Fiber Clothing',
                'description' => 'Clothing accessories, parts of garments, made from natural nettle (Girardinia diversifolia) or hemp fiber.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Wild Himalayan natural fiber product.',
                'is_popular' => true,
                'search_keywords' => 'allo, nettle fabric, natural fiber clothing, eco garment, himalayan nettle',
            ],
            [
                'code' => '6505.00.00',
                'wco_code' => '6505.00',
                'nepal_tariff_code' => '6505.00.00',
                'commodity_name' => 'Traditional Nepali Dhaka Topi & Woolen Beanies',
                'description' => 'Hats and other headgear, knitted or crocheted, or made up from lace, felt or other textile fabric.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Cultural handicraft item.',
                'is_popular' => true,
                'search_keywords' => 'dhaka topi, nepali cap, woolen beanie, winter hat, headgear',
            ],
            [
                'code' => '6202.93.00',
                'wco_code' => '6202.93',
                'nepal_tariff_code' => '6202.93.00',
                'commodity_name' => 'Down Winter Jackets & Mountaineering Parkas',
                'description' => 'Women or girls anoraks, windcheaters, ski jackets of man-made fibers padded with down/feather.',
                'category' => 'Textiles & Pashmina',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Trekking gear / down jacket.',
                'is_popular' => true,
                'search_keywords' => 'down jacket, trekking jacket, mountaineering parka, windcheater, winter coat',
            ],

            // ============================================================
            // 2. CARPETS, RUGS & FELT HANDICRAFTS
            // ============================================================
            [
                'code' => '5701.10.00',
                'wco_code' => '5701.10',
                'nepal_tariff_code' => '5701.10.00',
                'commodity_name' => 'Hand-Knotted Tibetan / Nepali Woolen Carpets',
                'description' => 'Carpets and other textile floor coverings, knotted, of wool or fine animal hair (60 to 150 knots/sq inch).',
                'category' => 'Carpets & Rugs',
                'standard_uom' => 'SQM',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Major Nepal export product. Central Carpet Association of Nepal endorsement recommended.',
                'is_popular' => true,
                'search_keywords' => 'carpet, woolen rug, tibetan rug, hand knotted carpet, floor covering, nepali carpet',
            ],
            [
                'code' => '5701.90.00',
                'wco_code' => '5701.90',
                'nepal_tariff_code' => '5701.90.00',
                'commodity_name' => 'Hand-Knotted Silk & Bamboo-Silk Blend Carpets',
                'description' => 'Carpets and other textile floor coverings, knotted, of silk, botanical silk or synthetic blends.',
                'category' => 'Carpets & Rugs',
                'standard_uom' => 'SQM',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'High-value luxury export item.',
                'is_popular' => false,
                'search_keywords' => 'silk carpet, bamboo silk rug, luxury carpet, hand knotted silk',
            ],
            [
                'code' => '5602.29.00',
                'wco_code' => '5602.29',
                'nepal_tariff_code' => '5602.29.00',
                'commodity_name' => 'Handmade Woolen Felt Crafts, Balls & Coasters',
                'description' => 'Felt articles, needleloom felt and stitch-bonded fiber fabric, handmade decorative balls, rugs, coasters, animal figures.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => '100% pure New Zealand / Tibetan sheep wool felted by hand.',
                'is_popular' => true,
                'search_keywords' => 'felt balls, felt craft, woolen felt, felt coaster, felt garland, felt toys, felted cat cave',
            ],
            [
                'code' => '6405.20.00',
                'wco_code' => '6405.20',
                'nepal_tariff_code' => '6405.20.00',
                'commodity_name' => 'Handmade Pure Wool Felt Slippers & Shoes',
                'description' => 'Footwear with outer soles and uppers of textile felt material.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'PRS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Non-leather, hand-felted footwear.',
                'is_popular' => true,
                'search_keywords' => 'felt slippers, woolen shoes, house slippers, felt booties, handmade footwear',
            ],
            [
                'code' => '5705.00.00',
                'wco_code' => '5705.00',
                'nepal_tariff_code' => '5705.00.00',
                'commodity_name' => 'Hemp & Jute Floor Mats & Braided Runners',
                'description' => 'Other carpets and floor coverings made of wild Himalayan hemp, nettle, or jute.',
                'category' => 'Carpets & Rugs',
                'standard_uom' => 'SQM',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Natural eco-friendly fiber.',
                'is_popular' => false,
                'search_keywords' => 'hemp rug, jute runner, floor mat, natural fiber rug',
            ],

            // ============================================================
            // 3. TEA, COFFEE, HONEY & AGRO-SPICES
            // ============================================================
            [
                'code' => '0902.10.00',
                'wco_code' => '0902.10',
                'nepal_tariff_code' => '0902.10.00',
                'commodity_name' => 'Himalayan Orthodox Black Tea',
                'description' => 'Black tea (fermented) and partly fermented tea, in immediate packings, grown in eastern hills of Ilam, Dhankuta, Panchthar.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Phytosanitary certificate required for international commercial clearance.',
                'is_popular' => true,
                'search_keywords' => 'tea, orthodox tea, black tea, ilam tea, golden tips, silver tips, loose leaf tea',
            ],
            [
                'code' => '0902.20.00',
                'wco_code' => '0902.20',
                'nepal_tariff_code' => '0902.20.00',
                'commodity_name' => 'Himalayan Organic Green Tea',
                'description' => 'Green tea (not fermented) in immediate packings.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Phytosanitary certificate recommended.',
                'is_popular' => true,
                'search_keywords' => 'green tea, organic tea, herbal tea, himalayan green tea',
            ],
            [
                'code' => '0901.11.00',
                'wco_code' => '0901.11',
                'nepal_tariff_code' => '0901.11.00',
                'commodity_name' => 'Nepal Arabica Specialty Coffee (Green Beans)',
                'description' => 'Coffee, not roasted, not decaffeinated, Arabica specialty hill-grown beans.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Coffee Board certificate / Phytosanitary.',
                'is_popular' => true,
                'search_keywords' => 'coffee, green coffee beans, arabica, specialty coffee, organic coffee',
            ],
            [
                'code' => '0901.21.00',
                'wco_code' => '0901.21',
                'nepal_tariff_code' => '0901.21.00',
                'commodity_name' => 'Artisanal Roasted Coffee Beans & Ground Coffee',
                'description' => 'Coffee, roasted, not decaffeinated, packaged for retail sale.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Packaged roasted coffee.',
                'is_popular' => true,
                'search_keywords' => 'roasted coffee, ground coffee, espresso beans, himalayan roasted coffee',
            ],
            [
                'code' => '0908.31.00',
                'wco_code' => '0908.31',
                'nepal_tariff_code' => '0908.31.00',
                'commodity_name' => 'Himalayan Large Cardamom (Alaichi)',
                'description' => 'Cardamoms, neither crushed nor ground, dried large Himalayan black cardamom pods.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Major cash crop export. Clean moisture proof packaging required.',
                'is_popular' => true,
                'search_keywords' => 'cardamom, large cardamom, alaichi, black cardamom, spices, spice pods',
            ],
            [
                'code' => '0910.11.00',
                'wco_code' => '0910.11',
                'nepal_tariff_code' => '0910.11.00',
                'commodity_name' => 'Dried Organic Ginger (Sutho / Sonth)',
                'description' => 'Ginger, neither crushed nor ground, dried organic hill ginger.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Phytosanitary inspection required.',
                'is_popular' => true,
                'search_keywords' => 'ginger, dry ginger, sutho, sonth, aduwa, organic ginger',
            ],
            [
                'code' => '0910.99.00',
                'wco_code' => '0910.99',
                'nepal_tariff_code' => '0910.99.00',
                'commodity_name' => 'Himalayan Timur (Sichuan Pepper / Prickly Ash)',
                'description' => 'Zanthoxylum armatum dried peppercorns, aromatic wild Himalayan culinary and medicinal spice.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Wild harvested Himalayan spice.',
                'is_popular' => true,
                'search_keywords' => 'timur, sichuan pepper, zanthoxylum, prickly ash, nepalese pepper, nepali timur',
            ],
            [
                'code' => '0409.00.00',
                'wco_code' => '0409.00',
                'nepal_tariff_code' => '0409.00.00',
                'commodity_name' => 'Wild Himalayan Cliff Honey / Mad Honey',
                'description' => 'Natural honey gathered from wild Apis laboriosa cliff bee nests in high Himalayas.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Lab test certificate / Food safety compliance for international air shipment.',
                'is_popular' => true,
                'search_keywords' => 'honey, cliff honey, wild honey, mad honey, raw honey, himalayan honey',
            ],
            [
                'code' => '0910.30.00',
                'wco_code' => '0910.30',
                'nepal_tariff_code' => '0910.30.00',
                'commodity_name' => 'Organic Himalayan Turmeric Powder (Besar)',
                'description' => 'Turmeric (curcuma), dried roots or ground powder with high curcumin content.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Food safety test report recommended.',
                'is_popular' => false,
                'search_keywords' => 'turmeric, besar, curcuma, organic turmeric, yellow spice',
            ],
            [
                'code' => '2501.00.00',
                'wco_code' => '2501.00',
                'nepal_tariff_code' => '2501.00.00',
                'commodity_name' => 'Himalayan Rock Salt (Pink Salt & Black Salt / Bire Noon)',
                'description' => 'Mineral rock salt and edible black salt crystals from Himalayan foothills.',
                'category' => 'Tea, Coffee & Agro',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Mineral salt for culinary / bath use.',
                'is_popular' => false,
                'search_keywords' => 'pink salt, himalayan salt, bire noon, black salt, rock salt, mineral salt',
            ],

            // ============================================================
            // 4. HERBS, AYURVEDA & SHILAJIT
            // ============================================================
            [
                'code' => '1211.90.00',
                'wco_code' => '1211.90',
                'nepal_tariff_code' => '1211.90.00',
                'commodity_name' => 'Pure Himalayan Shilajit Resin (Salajeet)',
                'description' => 'Purified mineral pitch / asphaltum punjabianum resin harvested from high Himalayan rock crevices.',
                'category' => 'Herbs & Ayurveda',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Ayurvedic Department clearance / Heavy metal test report recommended for US/EU.',
                'is_popular' => true,
                'search_keywords' => 'shilajit, salajeet, mumijo, mineral pitch, himalayan shilajit, fulvic acid',
            ],
            [
                'code' => '1211.90.10',
                'wco_code' => '1211.90',
                'nepal_tariff_code' => '1211.90.10',
                'commodity_name' => 'Cordyceps Sinensis (Yarsagumba)',
                'description' => 'Wild harvested caterpillar fungus from alpine meadows of Dolpa, Mugu, Darchula.',
                'category' => 'Herbs & Ayurveda',
                'standard_uom' => 'GMS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Department of Forest & Wildlife royalty clearance certificate mandatory.',
                'is_popular' => true,
                'search_keywords' => 'cordyceps, yarsagumba, yarshagumba, caterpillar fungus, alpine herb',
            ],
            [
                'code' => '3301.29.00',
                'wco_code' => '3301.29',
                'nepal_tariff_code' => '3301.29.00',
                'commodity_name' => 'Himalayan Essential Oils (Juniper, Wintergreen, Lemongrass)',
                'description' => 'Essential oils not elsewhere specified, steam distilled from wild aromatic Himalayan flora.',
                'category' => 'Herbs & Ayurveda',
                'standard_uom' => 'LTR',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'MSDS (Material Safety Data Sheet) required for air cargo (IATA dangerous goods check).',
                'is_popular' => true,
                'search_keywords' => 'essential oil, wintergreen oil, juniper oil, chamomile oil, lemongrass oil, aroma oil',
            ],
            [
                'code' => '3004.90.00',
                'wco_code' => '3004.90',
                'nepal_tariff_code' => '3004.90.00',
                'commodity_name' => 'Ayurvedic Herbal Medicines & Dietary Supplements',
                'description' => 'Medicaments consisting of mixed or unmixed products for therapeutic uses, put up in measured doses.',
                'category' => 'Herbs & Ayurveda',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Department of Drug Administration (DDA) registration details.',
                'is_popular' => true,
                'search_keywords' => 'ayurveda, herbal medicine, supplements, triphala, ashwagandha, herbal capsules',
            ],
            [
                'code' => '3307.41.00',
                'wco_code' => '3307.41',
                'nepal_tariff_code' => '3307.41.00',
                'commodity_name' => 'Traditional Hand-Rolled Incense Sticks & Cones (Agarbatti)',
                'description' => 'Agarbatti and other odoriferous preparations which operate by burning, hand-rolled in Kathmandu monasteries.',
                'category' => 'Herbs & Ayurveda',
                'standard_uom' => 'PKT',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Standard non-hazardous air shipment.',
                'is_popular' => true,
                'search_keywords' => 'incense, agarbatti, tibetan incense, herbal incense, aroma sticks, dhoop',
            ],

            // ============================================================
            // 5. HANDICRAFTS, STATUES & METALCRAFT
            // ============================================================
            [
                'code' => '8306.29.00',
                'wco_code' => '8306.29',
                'nepal_tariff_code' => '8306.29.00',
                'commodity_name' => 'Lost-Wax Cast Bronze & Copper Buddha Statues',
                'description' => 'Statuettes and other ornaments, of base metal (bronze, copper, brass), gold-gilded, hand-carved in Patan.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Department of Archaeology (Puratatwa Bibhag) non-antique export clearance certificate mandatory.',
                'is_popular' => true,
                'search_keywords' => 'statue, buddha statue, bronze statue, copper sculpture, tara statue, patan metalcraft, ganesh statue',
            ],
            [
                'code' => '9206.00.00',
                'wco_code' => '9206.00',
                'nepal_tariff_code' => '9206.00.00',
                'commodity_name' => 'Hand-Hammered Tibetan Singing Bowls & Gongs',
                'description' => 'Percussion musical instruments (cymbals, castanets, gongs, singing bowls of 7-metal alloy).',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Meditation / sound healing instrument.',
                'is_popular' => true,
                'search_keywords' => 'singing bowl, tibetan bowl, meditation bowl, sound healing, gong, tingsha cymbals',
            ],
            [
                'code' => '9701.91.00',
                'wco_code' => '9701.91',
                'nepal_tariff_code' => '9701.91.00',
                'commodity_name' => 'Hand-Painted Thanka / Paubha Buddhist Scroll Paintings',
                'description' => 'Paintings, drawings and pastels, executed entirely by hand, on cotton canvas with natural mineral pigments and 24K gold.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Department of Archaeology non-antique certificate required.',
                'is_popular' => true,
                'search_keywords' => 'thanka, thangka, paubha, mandala, buddhist painting, gold painting, scroll art',
            ],
            [
                'code' => '4420.10.00',
                'wco_code' => '4420.10',
                'nepal_tariff_code' => '4420.10.00',
                'commodity_name' => 'Hand-Carved Wooden Statuettes, Windows & Screens',
                'description' => 'Statuettes and other ornaments, of wood, traditional Newari peacock windows and panels.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Department of Archaeology / Forest clearance.',
                'is_popular' => true,
                'search_keywords' => 'wood carving, peacock window, wooden statue, carved panel, wooden craft',
            ],
            [
                'code' => '7113.11.00',
                'wco_code' => '7113.11',
                'nepal_tariff_code' => '7113.11.00',
                'commodity_name' => 'Handcrafted 925 Sterling Silver Jewelry & Filigree',
                'description' => 'Articles of jewelry and parts thereof, of silver, whether or not plated or clad with other precious metal.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'GMS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Nepal Gem & Jewelry Association / Federation certificate.',
                'is_popular' => true,
                'search_keywords' => 'silver jewelry, 925 silver, ring, pendant, necklace, earring, filigree, silver bracelet',
            ],
            [
                'code' => '7116.20.00',
                'wco_code' => '7116.20',
                'nepal_tariff_code' => '7116.20.00',
                'commodity_name' => 'Natural Rudraksha Beads, Bodhi Seed Malas & Necklaces',
                'description' => 'Articles of precious or semi-precious stones (natural, synthetic or reconstructed), spiritual prayer beads.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Nepal botanical export.',
                'is_popular' => true,
                'search_keywords' => 'rudraksha, mala, prayer beads, bodhi seed, 5 mukhi, nepali rudraksha, japa mala',
            ],
            [
                'code' => '8306.10.00',
                'wco_code' => '8306.10',
                'nepal_tariff_code' => '8306.10.00',
                'commodity_name' => 'Ritual Bells, Dorje, Ghanta & Butter Lamps',
                'description' => 'Bells, gongs and the like, non-electric, of base metal; statuettes and other ornaments.',
                'category' => 'Handicrafts & Art',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Buddhist ritual object.',
                'is_popular' => false,
                'search_keywords' => 'bell, ghanta, dorje, vajra, butter lamp, ritual object, brass bell',
            ],

            // ============================================================
            // 6. LOKTA PAPER & STATIONERY
            // ============================================================
            [
                'code' => '4802.10.00',
                'wco_code' => '4802.10',
                'nepal_tariff_code' => '4802.10.00',
                'commodity_name' => 'Handmade Lokta Paper Sheets & Raw Paper',
                'description' => 'Handmade paper and paperboard, made from Daphne bholua and Daphne papyracea bark fibers.',
                'category' => 'Lokta Paper & Stationery',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Tree-free, non-toxic, eco-friendly paper product.',
                'is_popular' => true,
                'search_keywords' => 'lokta, handmade paper, lokta paper, daphne paper, eco paper, raw sheets',
            ],
            [
                'code' => '4820.10.00',
                'wco_code' => '4820.10',
                'nepal_tariff_code' => '4820.10.00',
                'commodity_name' => 'Lokta Leather-Bound Journals, Diaries & Notebooks',
                'description' => 'Registers, account books, notebooks, order books, receipt books, letter pads, memorandum pads, diaries.',
                'category' => 'Lokta Paper & Stationery',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Artisanal stationery.',
                'is_popular' => true,
                'search_keywords' => 'journal, diary, notebook, lokta journal, leather notebook, handmade diary',
            ],
            [
                'code' => '4901.99.00',
                'wco_code' => '4901.99',
                'nepal_tariff_code' => '4901.99.00',
                'commodity_name' => 'Printed Books, Literature & Educational Guides',
                'description' => 'Printed books, brochures, leaflets and similar printed matter, in single sheets or bound.',
                'category' => 'Lokta Paper & Stationery',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Duty-free in most jurisdictions under Florence Agreement.',
                'is_popular' => true,
                'search_keywords' => 'book, books, printed matter, catalog, manual, publication',
            ],
            [
                'code' => '4907.00.00',
                'wco_code' => '4907.00',
                'nepal_tariff_code' => '4907.00.00',
                'commodity_name' => 'Commercial Documents, Certificates & Passports',
                'description' => 'Unused postage, revenue or similar stamps; stamp-impressed paper; banknotes; cheque forms; stock, share or bond certificates.',
                'category' => 'Lokta Paper & Stationery',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Non-dutiable commercial document.',
                'is_popular' => true,
                'search_keywords' => 'documents, certificate, passport, contract, legal paper, letter, air waybill',
            ],

            // ============================================================
            // 7. LEATHER, HEMP & TRAVEL GEAR
            // ============================================================
            [
                'code' => '4202.22.00',
                'wco_code' => '4202.22',
                'nepal_tariff_code' => '4202.22.00',
                'commodity_name' => 'Pure Himalayan Hemp Backpacks & Shoulder Bags',
                'description' => 'Handbags, whether or not with shoulder strap, including those without handle, with outer surface of textile materials (wild hemp).',
                'category' => 'Leather, Hemp & Bags',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Hemp textile product.',
                'is_popular' => true,
                'search_keywords' => 'hemp bag, hemp backpack, rucksack, boho bag, shoulder bag, travel bag',
            ],
            [
                'code' => '4202.31.00',
                'wco_code' => '4202.31',
                'nepal_tariff_code' => '4202.31.00',
                'commodity_name' => 'Genuine Leather Wallets, Purses & Cardholders',
                'description' => 'Articles of a kind normally carried in the pocket or in the handbag, with outer surface of leather or of composition leather.',
                'category' => 'Leather, Hemp & Bags',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Genuine water buffalo or goat leather.',
                'is_popular' => true,
                'search_keywords' => 'wallet, leather wallet, purse, cardholder, money clip, leather goods',
            ],
            [
                'code' => '4203.29.00',
                'wco_code' => '4203.29',
                'nepal_tariff_code' => '4203.29.00',
                'commodity_name' => 'Genuine Leather Motorcycle & Work Gloves',
                'description' => 'Gloves, mittens and mitts, of leather or of composition leather, other than sports gloves.',
                'category' => 'Leather, Hemp & Bags',
                'standard_uom' => 'PRS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Leather craftsmanship.',
                'is_popular' => false,
                'search_keywords' => 'leather gloves, motorcycle gloves, riding gloves, work gloves',
            ],
            [
                'code' => '4202.12.00',
                'wco_code' => '4202.12',
                'nepal_tariff_code' => '4202.12.00',
                'commodity_name' => 'Travel Luggage, Duffel Bags & Suitcases',
                'description' => 'Trunks, suit-cases, vanity-cases, executive-cases, brief-cases, school satchels and similar containers of textile or plastics.',
                'category' => 'Leather, Hemp & Bags',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Travel gear.',
                'is_popular' => true,
                'search_keywords' => 'duffel bag, luggage, suitcase, travel bag, gym bag',
            ],

            // ============================================================
            // 8. ELECTRONICS & ACCESSORIES
            // ============================================================
            [
                'code' => '8517.70.00',
                'wco_code' => '8517.70',
                'nepal_tariff_code' => '8517.70.00',
                'commodity_name' => 'Mobile Phone Accessories & Spare Parts',
                'description' => 'Parts of telephone sets and other apparatus for the transmission or reception of voice, images or other data.',
                'category' => 'Electronics',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Electronic accessories.',
                'is_popular' => true,
                'search_keywords' => 'phone case, mobile screen, charging cable, phone accessories, tempered glass',
            ],
            [
                'code' => '8504.40.00',
                'wco_code' => '8504.40',
                'nepal_tariff_code' => '8504.40.00',
                'commodity_name' => 'Power Adapters & USB Wall Chargers',
                'description' => 'Static converters (e.g. rectifiers, battery chargers, power supplies).',
                'category' => 'Electronics',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'CE/FCC certification mark check.',
                'is_popular' => false,
                'search_keywords' => 'charger, power adapter, usb charger, wall plug, power supply',
            ],
            [
                'code' => '8518.30.00',
                'wco_code' => '8518.30',
                'nepal_tariff_code' => '8518.30.00',
                'commodity_name' => 'Headphones, Earphones & Audio Headsets',
                'description' => 'Headphones and earphones, whether or not combined with a microphone.',
                'category' => 'Electronics',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Wireless / wired consumer audio.',
                'is_popular' => true,
                'search_keywords' => 'headphones, earphones, earbuds, headset, airpods, bluetooth audio',
            ],
            [
                'code' => '8471.30.00',
                'wco_code' => '8471.30',
                'nepal_tariff_code' => '8471.30.00',
                'commodity_name' => 'Portable Laptops & Tablet Computers',
                'description' => 'Portable automatic data processing machines, weighing not more than 10 kg, consisting of at least a central processing unit, keyboard and display.',
                'category' => 'Electronics',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Lithium ion battery section II declaration required (IATA UN3481).',
                'is_popular' => false,
                'search_keywords' => 'laptop, notebook computer, macbook, tablet, ipad, computer',
            ],

            // ============================================================
            // 9. GENERAL MERCHANDISE, SAMPLES & PERSONAL EFFECTS
            // ============================================================
            [
                'code' => '9803.00.00',
                'wco_code' => '9803.00',
                'nepal_tariff_code' => '9803.00.00',
                'commodity_name' => 'Personal Effects & Used Household Goods',
                'description' => 'Used personal clothing, books, footwear and household items belonging to an individual.',
                'category' => 'General Merchandise',
                'standard_uom' => 'KGS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Non-commercial personal shipment. Declare "Personal Effects - Not for Resale".',
                'is_popular' => true,
                'search_keywords' => 'personal effects, used clothes, household items, personal belongings, luggage, relocation',
            ],
            [
                'code' => '9801.00.00',
                'wco_code' => '9801.00',
                'nepal_tariff_code' => '9801.00.00',
                'commodity_name' => 'Commercial Product Samples (Value for Customs Only)',
                'description' => 'Samples of negligible value intended solely for soliciting orders.',
                'category' => 'General Merchandise',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Commercial sample - not for sale.',
                'is_popular' => true,
                'search_keywords' => 'samples, trade sample, fabric swatch, commercial sample, prototype',
            ],
            [
                'code' => '9506.99.00',
                'wco_code' => '9506.99',
                'nepal_tariff_code' => '9506.99.00',
                'commodity_name' => 'Trekking & Mountaineering Equipment / Poles',
                'description' => 'Articles and equipment for general physical exercise, gymnastics, athletics, other sports or outdoor games.',
                'category' => 'General Merchandise',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Mountaineering / trekking gear.',
                'is_popular' => true,
                'search_keywords' => 'trekking pole, sleeping bag, crampons, ice axe, climbing gear, outdoor equipment',
            ],
            [
                'code' => '9503.00.00',
                'wco_code' => '9503.00',
                'nepal_tariff_code' => '9503.00.00',
                'commodity_name' => 'Handmade Wooden & Plush Toys',
                'description' => 'Tricycles, scooters, pedal cars and similar wheeled toys; dolls carriages; dolls; other toys; reduced-size models.',
                'category' => 'General Merchandise',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'Child safety conformity.',
                'is_popular' => false,
                'search_keywords' => 'toys, wooden toy, stuffed animal, plush toy, puppet',
            ],
            [
                'code' => '3926.90.00',
                'wco_code' => '3926.90',
                'nepal_tariff_code' => '3926.90.00',
                'commodity_name' => 'Molded Plastic Articles & Household Containers',
                'description' => 'Other articles of plastics and articles of other materials of headings 39.01 to 39.14.',
                'category' => 'General Merchandise',
                'standard_uom' => 'PCS',
                'export_duty_rate' => 0.00,
                'customs_notes' => 'General plastic goods.',
                'is_popular' => false,
                'search_keywords' => 'plastic container, plastic article, box, kitchenware plastic',
            ],
        ];

        foreach ($commodities as $item) {
            HsCode::updateOrCreate(
                ['code' => $item['code']],
                $item
            );
        }
    }
}
